Repository North-Seattle-College/ad440-winter2020-thursday-repo, pull requests merged in 2020-03, with the labels that each got.

#185 putProperty done
  API/property/PUT/awsLambda.zip
  API/property/PUT/package-lock.json
  API/property/PUT/putProperty.js
Labels: api-team

#181 feature-sprint3-dereje: api for get all keyholder created
  API/keyholder/get/index.js
  API/keyholder/get/package.json
Labels: api-team

#187 Feature-sprint3-han-Implement authentication using AWS Cognito
  UI/UserPool.js
  UI/src/App.js
  UI/src/Components/Account.js
  UI/src/Components/Login.js
  UI/src/Components/Signup.js
  UI/src/Components/Status.js
Labels: task, ui-team

#245 Update .gitignore, allow package.json
  .gitignore
Labels: bug

#231 Feature sprint4 mattyplo
  .travis.yml
  Automation/TravisScripts/deployLambdas.py
  Automation/TravisScripts/traverseDirectories.py
Labels: devops-team

#289 Feature sprint5 quincypowell
  UI/package.json
  UI/public/React-icon.svg
  UI/public/UmanoPM-Logo.png
  UI/src/Actions/Session.js
  UI/src/App.js
  UI/src/App2.js
  UI/src/Components/Account.css
  UI/src/Components/Account.js
  UI/src/Components/AddKey.css
  UI/src/Components/AddKey.js
  UI/src/Components/AddKeyholder.css
  UI/src/Components/AddKeyholder.js
  UI/src/Components/AddPropertyMethod.js
  UI/src/Components/CheckoutKey.js
  UI/src/Components/Dashbord.css
  UI/src/Components/Dashbord.js
  UI/src/Components/Footer.js
  UI/src/Components/FormAddKey.js
  UI/src/Components/Home.js
  UI/src/Components/Login.js
  UI/src/Components/Logout.js
  UI/src/Components/Navbar.css
  UI/src/Components/SearchBar.js
  UI/src/Components/SideBar.js
  UI/src/Components/Signup.js
  UI/src/Components/Status.js
  UI/src/Components/Table.js
  UI/src/Components/TopBar.js
  UI/src/Components/WorkingArea.js
  UI/src/Components/keyholder.json
  UI/src/Components/tableLayout.css
  UI/src/Components/tableLayout.js
  UI/src/Config/App-config.json
  UI/src/Constants/actionTypes.js
  UI/src/NoMatch.js
  UI/src/Routes/Callback.js
  UI/src/Routes/Home.css
  UI/src/Routes/Home.js
  UI/src/Routes/logo.svg
  UI/src/apiurlbase.js
  UI/src/index.js
  UI/src/lib/CognitoUtils.js
  UI/src/reducers/index.js
  UI/src/reducers/session.js
  UI/src/staticResources.js
  UI/src/store/index.js
Labels: task, ui-team

#290 Feature sprint5 quincypowell2
  UI/src/Components/AddKey.js
  UI/src/Components/AddProperty.css
  UI/src/Components/AddProperty.js
  UI/src/Components/CheckoutKey.js
Labels: task, ui-team

#294 Feature sprint5 quincypowell2
  UI/package-lock.json
  UI/src/Components/AddKey.js
  UI/src/Components/AddKeyholder.js
Labels: task, ui-team

#300 Feature sprint5 quincypowell2
  UI/package-lock.json
  UI/src/Components/AddProperty.js
  UI/src/Components/CheckoutKey.js
  UI/src/Components/Dashboard.css
  UI/src/Components/Dashboard.js
  UI/src/Components/SelectKeyholderModal.css
  UI/src/Components/SelectKeyholderModal.js
  UI/src/Components/WorkingArea.js
Labels: task, ui-team

#308 Feature sprint5 untamedlaw
  API/property/get/index.js
  API/property/get/package.json
  API/property/post/index.js
  API/property/post/package.json
Labels: api-team, task

#312 very minor changes. Removed all debug statements. Removed any active …
  UI/src/Components/AddKey.js
  UI/src/Components/AddProperty.css
  UI/src/Components/AddProperty.js
  UI/src/Components/CheckoutKey.js
  UI/src/Components/SelectKeyholderModal.js
  UI/src/Components/SelectPropertyModal.js
  UI/src/Components/WorkingArea.js
Labels: task, ui-team
